buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "GTNH Maven"
            url = "https://nexus.gtnewhorizons.com/repository/public/"
        }
    }
    dependencies {
        classpath 'com.gtnewhorizons.retrofuturagradle:com.gtnewhorizons.retrofuturagradle.gradle.plugin:1.4.9'
    }
}

apply plugin: 'com.gtnewhorizons.retrofuturagradle'

version = "7.3.2.1"
def llibrary_version = "1.5.2"
group = "fossilsarcheology"

base {
    archivesName = "fossilsarcheology"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

minecraft {
    useDependencyAccessTransformers = false
    injectedTags.put('FML_AT', 'fossil_at.cfg')
}

jar {
    manifest {
        attributes 'FMLAT': 'fossil_at.cfg'
    }
}

repositories {
    mavenCentral()
    maven {
        url "https://cursemaven.com"
    }
}

dependencies {
    implementation ("curse.maven:llibrary-243298:5718845")
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.mcVersion.get()
    inputs.property "llibrary_version", llibrary_version
    
    filteringCharset 'UTF-8'

    from(sourceSets.main.resources.srcDirs) {
        filesMatching("mcmod.info") {
            expand "version": project.version, "mcversion": project.minecraft.mcVersion.get(), "llibrary_version": llibrary_version
        }
    }
}
